using System;
using NServiceBus;

namespace SimpleMatrix.WebSite
{
    // This code is generated by ServiceMatrix
    public class GeneratedWebInitialization : INeedInitialization
    {
        public void Init()
        {
        }
    }
}
